language: ruby
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
sudo: false
before_install: gem install bundler
addons:
  code_climate:
    repo_token: 4d2ac735662a2a4c0f7eb7862f5b451be4617cf1fb5913876d2dc3dba1bf5ffe
